# Generated by Django 4.1.3 on 2023-04-18 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bmpapp', '0009_product_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='date',
        ),
    ]
