# Generated by Django 4.1.3 on 2023-04-18 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmpapp', '0010_remove_product_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.png', upload_to='profile_pics'),
        ),
    ]
