# Generated by Django 4.1.3 on 2023-05-17 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bmpapp', '0012_alter_order_transaction_id_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='user',
        ),
    ]
