# Generated by Django 4.1.3 on 2023-05-21 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bmpapp', '0014_commments_post_delete_blog_commments_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='date_addded',
            new_name='date_added',
        ),
    ]
