# Generated by Django 4.1.3 on 2023-05-21 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bmpapp', '0015_rename_date_addded_post_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commments',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='bmpapp.post'),
        ),
    ]
