# Generated by Django 4.1.3 on 2023-05-24 15:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bmpapp', '0017_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commments',
            name='email',
        ),
        migrations.RemoveField(
            model_name='commments',
            name='name',
        ),
        migrations.AddField(
            model_name='commments',
            name='users',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
