# Generated by Django 4.1.3 on 2023-05-28 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmpapp', '0021_alter_packages_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='packages',
            old_name='description',
            new_name='description1',
        ),
        migrations.AddField(
            model_name='packages',
            name='description2',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='packages',
            name='description3',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='packages',
            name='description4',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='packages',
            name='description5',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='packages',
            name='description6',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='packages',
            name='description7',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='packages',
            name='description8',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
