# Generated by Django 4.1.3 on 2023-05-28 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmpapp', '0022_rename_description_packages_description1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packages',
            name='description2',
        ),
        migrations.RemoveField(
            model_name='packages',
            name='description3',
        ),
        migrations.RemoveField(
            model_name='packages',
            name='description4',
        ),
        migrations.RemoveField(
            model_name='packages',
            name='description5',
        ),
        migrations.RemoveField(
            model_name='packages',
            name='description6',
        ),
        migrations.RemoveField(
            model_name='packages',
            name='description7',
        ),
        migrations.RemoveField(
            model_name='packages',
            name='description8',
        ),
        migrations.AlterField(
            model_name='packages',
            name='description1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
