# Generated by Django 4.1.3 on 2023-05-28 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bmpapp', '0023_remove_packages_description2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='packages',
            old_name='description1',
            new_name='description',
        ),
    ]
