# Generated by Django 4.1.3 on 2023-05-28 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmpapp', '0024_rename_description1_packages_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packages',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
