# Generated by Django 4.1.3 on 2023-05-29 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmpapp', '0027_alter_packages_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='packages',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='packages',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
